version: "3.7"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - "SECRET_KEY=change_me_later"
      - "DJANGO_SETTINGS_MODULE=hydra.settings.dev"
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres
    networks:
      - mynetwork
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
networks:
  mynetwork: