# Generated by Django 3.2.3 on 2021-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_spec',
            name='k8s_job_labels',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
