# Generated by Django 3.2.3 on 2021-08-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch_imu',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='batch_photo',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='batch_photo',
            name='num_photos',
        ),
    ]
