# Generated by Django 3.2.3 on 2021-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210810_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_photo',
            name='useless_field',
            field=models.BooleanField(default=True, help_text=('This field is only being added as serialized models ', 'need a field so they can accept data. Please refactor')),
            preserve_default=False,
        ),
    ]
