# Generated by Django 3.2.3 on 2021-08-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_spec_k8s_job_labels'),
        ('api', '0004_alter_batch_photo_useless_field'),
    ]

    operations = [
    ]
