# Generated by Django 3.2.3 on 2021-10-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20210811_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch_photo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='processed_imu',
            name='batch_imu',
        ),
        migrations.RemoveField(
            model_name='processed_imu',
            name='batch_job',
        ),
        migrations.RemoveField(
            model_name='processed_photo',
            name='batch_job',
        ),
        migrations.RemoveField(
            model_name='processed_photo',
            name='batch_photo',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='job_definition',
            name='data_type',
        ),
        migrations.AddField(
            model_name='batch_job',
            name='batches',
            field=models.ManyToManyField(help_text='The batches that this job took place on', to='api.Batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job_spec',
            name='created_by',
            field=models.CharField(choices=[('greg', 'greg@mobilizedconstruction.com'), ('charlotte', 'charlotte@mobilizedconstruction.com'), ('tirtha', 'tirtha@mobilizedconstruction.com'), ('anders', 'anders@mobilizedconstruction.com'), ('jens', 'jens@mobilizedconstruction.com'), ('chris', 'chris@mobilizedconstruction.com'), ('kevin', 'kevin@mobilizedconstruction.com')], default='greg', help_text='The user who defined the job spec', max_length=20),
        ),
        migrations.DeleteModel(
            name='Batch_IMU',
        ),
        migrations.DeleteModel(
            name='Batch_Photo',
        ),
        migrations.DeleteModel(
            name='Job_DataType',
        ),
        migrations.DeleteModel(
            name='Processed_IMU',
        ),
        migrations.DeleteModel(
            name='Processed_Photo',
        ),
    ]
