# Generated by Django 3.2.3 on 2021-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_separate_job_datatypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_job',
            name='created_on_k8s',
            field=models.BooleanField(default=False, help_text='Flag denoting whether the job has been created on k8s.'),
        ),
        migrations.AddField(
            model_name='batch_job',
            name='scheduled',
            field=models.BooleanField(default=False, help_text='Flag denoting whether the job has been scheduled'),
        ),
    ]
