# Generated by Django 3.2.3 on 2021-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211027_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(default=None, help_text='Time batch information was first sent to this server.', null=True),
        ),
    ]
